version: '3'

services:
  e-store:
    container_name: e-store
    build:
      context: ./e-store
      dockerfile: Dockerfile
    environment:
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      GITHUB_ID: ${GITHUB_ID}
      GITHUB_SECRET: { GITHUB_SECRET }
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
    volumes:
      - ./e-store/src:/app/src
      - ./e-store/public:/app/public
    restart: always
    ports:
      - 3000:3000
